In [21]:
import numpy as np
arr = np.array([10, 20, 30, 40 , 50 , 60])     #INDEXING 

In [22]:
print(arr[2])                             

30


In [32]:
print(arr[0:2])           #SLICING         

[10 20]


In [33]:
print(arr[:5])

[10 20 30 40 50]


In [34]:
print(arr[::2])

[10 30 50]


In [35]:
idx = [0, 2, 4]          #FANCY INDEXING 
print(idx)              

[0, 2, 4]


In [36]:
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])         #BOOLEAN MASKING 

[30 40 50 60]


In [49]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [45]:
flat = arr.flatten()

In [48]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])