In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2       # Vectorized operation
print(result)

[ 1  4  9 16 25]


In [6]:
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)

[11 12 13 14 15]


In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2  # Element-wise addition
print(result)  

[11 22 33]
